package alipay.manage.api.channel.deal.mypay;

public class MyPayUtil {
    public final static  String NOTIFY = "/mypay-notify";
    public final static  String PRIVATE_KEY = "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJ36fRMzwGE5PEzk+2nurRVYzwFhAzsuX0muvi/KfaOLTmSIxsN/lexm9vhM8WylYxznKa/GNUo8mePbn+qqKtmpnoyUMRhdHEr8NMMNNtDQwxIDvPTaMuigIFba2ygXAQdy6c6OoAZOjQYM8DQLtRwZz8k+Io9hxiw0bv5kqCnHAgMBAAECgYBE5cfCpiFSxYl856iWTJeD5dVx/oNQPiskkWc0pJUizFCGG/jDrlMOZOF07OmlvoN5SX+uvzzigYeEDnax+0DwORjk1tOdZOu0bTupym3VsQkPGAUxVdeZc45eNxIYTV5ZyQnGrdI94wAkEYuMsqa8rlFldlH2K7GcljEenj+kAQJBANPaedR2ZlQKekqP3XMCfxvstpXOUgXeQagzNIDGV1Ti1LGEyu4Dttnj0WoTIJ1vJT7O36C0bmfWDjIOAF3tEQECQQC+5gBxqKME6/hYgaJaz/MP8CIh/qyeZy5UV890LaYlrLTrYzCFm10Tn7zexPHFDPziAcrTDNGos+hqC9MqTfLHAkAJ8lcH/6scRQWq3IhULwjSwdFsxSwatG22vPi5FxbgmGnOD+MLO8dpAYZCibVdTuubwFDFldMdMvKlrPydbFUBAkAAp8d+nGaa4LiEjUVibG5YMqnbVgV/sbj9/yMuMe3tGS+x0zBadRMXuyep2CFAXPANUpZArT2XB68XlhzOe2AHAkBpajRkEs5ggzU51rq1mTGgmdoyRX22lTY54QiSZDoSFbNFZrMiW3m50tY6/0yLZUuUDwm5GO609XYaLC8bQPdA";
    public final static  String PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+EgLSZ1ZgosawhQA0I3ysznJ+FV2n1Gxp+aHo/hm99lfAZO5bJp1DJsHbHJtOaXcFv35HhrltolFXIC6TBnOS4S/ACB8E5SsnfCKm/JYGAxXIfbq4gaOuwZo5WmcCX9PZ8tWsy1XEt1dLZ+lL70F+3OaAhaHuU4/rKZqsJbp0RQIDAQAB";




}
