eureka : 
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    # 是否使用ip注册
    prefer-ip-address : true
    # ${spring.cloud.client.ip-address}:${server.port}  局域网这样配置
    #  本地调试则要直接写死ip 【这个ip为注册时候的 调用ip】  47.52.108.99
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 注册ip地址http://182.16.89.146
    ip-address: ${spring.cloud.client.ip-address}
    # 注册ip端口
    non-secure-port : ${server.port}
    hostname: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: otc-zuul-server
zuul:
  strip-prefix: false
  routes:
    api-a:
      path: /api-alipay/**
      serviceId: otc-alipay-server
    api-b:
      path: /api-dealpay/**
      serviceId: otc-dealpay-server
    api-c:
      path: /api-file/**
      serviceId: otc-file-server
  host:
    maxTotalConnections: 6000000
    maxPerRouteConnections: 600000
  max:
    host:
      connections: 1000000
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    c4i-store:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
            ribbon:
              ReadTimeout: 600000
              ConnectTimeout: 600000